### ISSUE TITLE
Page Width Consistency Issue with Obsidian SNW Plugin

### ISSUE THREAD

**Issue by sfsdfc** [TfTHacker/obsidian42-strange-new-worlds#115]
Hello,

I use the following CSS code to set the page width in Obsidian:

```
body {
  --user-custom-width: 703px !important;
  --file-line-width: var(--user-custom-width);
}
```

When SNW is not enabled, the page width remains consistent in both reading and preview modes. However, when I enable SNW, the page width becomes narrower in preview mode, as shown in the attached image.

![image](https://github.com/TfTHacker/obsidian42-strange-new-worlds/assets/133151823/59b0eb4b-ac7f-4fe7-9772-4778ed815da5)

Could you please advise on which parameters to adjust to maintain consistent page width when NSW is enabled? Thank you!

**Comment by TfTHacker** [comment]
This is a side effect of having references showing in gutters, because when gutters are enabled, Obsidian pushes out the margin. Also different themes handle gutters differently, so in some cases this extra margin is visible, while in other themes its not.

Two solutions:

1) In most cases, the gutter option is not needed, it is for handling a few edge cases. So it can be disabled:

<img width="804" alt="image" src="https://github.com/user-attachments/assets/482996de-5191-4a37-8ab2-5a502f009af3">

2) Use a theme that handles gutters the way you would like them to appear.

Thank you for your issue.
