### ISSUE TITLE
Feature Request - Linking capped and uncapped links as one

### ISSUE THREAD

**Issue by sunsurfsnow** [TfTHacker/obsidian42-strange-new-worlds#131]
It would be great to link together Capitalised and non-capitalised words under the same link. Ie. "Hypertension" and "hypertension" should be recognised as one link, not two.

**Comment by TfTHacker** [comment]
Hi, thank you for your feedback. I've been testing this with the current beta, and links are not case-sensitive unless they use headers or block IDs. Essentially, these Obsidian elements are case-sensitive by nature. If you'd like, you can try the beta with BRAT. Otherwise, in the next week or two, I will release version "2.0.0," and you can see if it performs as desired then.

**Comment by sunsurfsnow** [comment]
Thanks for the update. I appreciate the changes and it helps a lot.
