### ISSUE TITLE
File response speed

### ISSUE THREAD

**Issue by arpcn** [TfTHacker/obsidian42-strange-new-worlds#152]
I have been using V1.2.5 before, and the file response speed is acceptable. Recently updated to V2.1.5, I found that the app was severely lagging. I tried V2.1.4 and V2.1.2, but the lag was still the same. May I ask how to solve this problem? Thank you!

**Comment by dv46** [comment]
I have also upgraded from an earlier version (1.2.3) to V2.1.5 and also have a small freeze around every 1 second. It doesn't matter if that page has any links, it also lags on newly created empty pages (although I have other tabs open if that's relevant)
In a previous version I had issues when internally linking other pages where it became extremely laggy as I typed and Obsidian gave me page recommendations to link. What helped there was setting the cache tuning to 2500ms and the problem was gone
That option was sadly removed from V1 to V2, so I can't test if it would fix my problem again this time

**Comment by TfTHacker** [comment]
I appreciate these reports, as performance is very important to me. I have to say that these versions you both were running on are very old. Is it possible you haven't updated plugins in your vault for some time? 

From version 2.0, SNW was rewritten internally in how it processes links and the focus was on performance improvements. The metrics showed it to be significantly better. So I am baffled at what it could be.

Could you do me a favor, disable SNW for a few days, and see if the issue goes away?

**Comment by dv46** [comment]
Yes, I haven't updated my plugins for some time.
Before commenting on this issue I checked if SNW is actually the problem by disabling it and the problems were gone once I disabled it.

But I've just tested it again now and have no performance issues anymore. So that's great! 
I will continue testing it and comment on this or create a new issue if problems come up again.
