### ISSUE TITLE
strange-new-worlds misses all sorts of links

### ISSUE THREAD

**Issue by jiajiala** [TfTHacker/obsidian42-strange-new-worlds#154]
![image](https://github.com/user-attachments/assets/9eefe50a-82db-49df-836b-0cc8a1010892)

When you use strange-e-like worldsIn the above content,
 all the links can be correctly found in the obsidian
 But only [[test#Y]] was identified correctly,
Other cases are not identified

**Comment by TfTHacker** [comment]
The first scenario should now be addressed with update 2.2.0. Thank you for reporting this issue.

However, in general SNW isn't officially supporting reference ID's in headers. I know Obsidian supports this in the UI, but it turns out to be very difficult to parse. (Pull requests welcome if someone wants to go further with this request).
