### ISSUE TITLE
Help needed with possibly expected behaviour with Dataview

### ISSUE THREAD

**Issue by looneyapache** [TfTHacker/obsidian42-strange-new-worlds#22]
I have a dataview query on top of a "asset" note, but I'm not sure if this is a likely result.

The first result of the dataview query is now displayed in a popup window on mouse over (among other dataview links text )  - prior to the presentation of the actual note text 
This is a screenshot. (I was anticipating the text that follows the dataview block) , or if there is any way that I could avoid/ignore dataview blocks/queries.

Please help if this may be expected/intended outcome.

![Obsidian_12hPWWsOhq](https://user-images.githubusercontent.com/10562851/197448680-49e39d38-5ede-400f-9f21-e55236940fae.png)

**Comment by TfTHacker** [comment]
Hi! Would  you please do a loom video or something of that sort so I can better see the flow?

**Comment by looneyapache** [comment]
Here is the File 1 (Accounting Equation)
https://user-images.githubusercontent.com/10562851/197450491-6bca51f2-1608-41b5-88b1-5544d3c0a385.mp4

This is File 2 (Assets.md)

https://user-images.githubusercontent.com/10562851/197450754-9f834eca-1697-45b8-b8dc-3823e305e42d.mp4

If I missed something, just let me know.

**Comment by TfTHacker** [comment]
You were fast! Thank you.

So the question is: should dataview content appear in the popup? I think the answer is yes, since the popup is using Obsidian's Markdown rendering engine. Any registered "renderer' will get called. So I would not be surprised if dataview renders. However, I see from my own testing that some components are not rendered (Example block id references).

Let me know if this answers your question.

**Comment by looneyapache** [comment]
Indeed,
I needed to make sure that this was truly the case as it was expected behavior.
Thank you for conformation!

I appreciate your support.   👍 🙇
