### ISSUE TITLE
Conflict with dataview plugin

### ISSUE THREAD

**Issue by Yubuxin** [TfTHacker/obsidian42-strange-new-worlds#3]
This plugin may cause the dataview rendering improperly.

**Comment by TfTHacker** [comment]
Tnx for fast feedback! I pulled up a few of my Dataview files and they are rendering ok. 

Can you provide me some examples?

**Comment by Yubuxin** [comment]
@TfTHacker Thanks for relying. Just like this:

![image](https://user-images.githubusercontent.com/87011715/189278462-b608dc81-d2df-4dfd-ad9d-76f32325dc2c.png)

When I turn this plugin on, the to-do list aggregated by dataview will show imcomplete.

**Comment by TfTHacker** [comment]
What theme are you using? Also are you on Insider build 0.16.2

I ask because I am using the default theme and not seeing this problem. Also are you using another task plugin? (I will try to duplicate your environment.

Can you share the Markdown for this file (the part with yourheading and dataview query)

**Comment by Yubuxin** [comment]
> What theme are you using? Also are you on Insider build 0.16.2
> 
> I ask because I am using the default theme and not seeing this problem. Also are you using another task plugin? (I will try to duplicate your environment.
> 
> Can you share the Markdown for this file (the part with yourheading and dataview query)

The theme I use is minimal 5.3.2, and it seems that it's nothing to do with theme, because when I switch to the default theme, the problem still occurs.

I'm not on insider build and the version I'm using is Obsidian 0.15.9. And I'm not using another task plugin either.

The dataview query (and the heading) I use here is pretty common:

## 「计划中」

```dataview
task
from !"journal"
where !completed and due > date(eow)
sort due
```

**Comment by TfTHacker** [comment]
Ok. this might be the issue then. My current dev updates are for the insider build. This is a problem with the old build. It may try to load the newer version.

I would suggest manually installing version 0.0.01 to roll back to a previous build. Likely when insider release is pushed out, this problem will resolve itself since the code is optimized for Obisidan 0.16.2 or greater.

Sorry for the hassle. we are in an odd time with Obsidian in Beta and Strange New Worlds Plugin also in early development.
