### ISSUE TITLE
[feat] Respect excluded file list

### ISSUE THREAD

**Issue by heliostatic** [TfTHacker/obsidian42-strange-new-worlds#33]
Current functionality is great, but somewhat hindered by my use of a changelog file -- I have this set as an excluded file in Obsidian, but it doesn't appear that list is respected by this plugin. Would it be possible to exclude those files (a plugin that does so is Omnisearch, e.g.)?

**Comment by TfTHacker** [comment]
interesting idea. can you explain how the changelog file and what do you mean by "hindered"? I am thinking about some of these types of details these days, so good timing with your feedback.

**Comment by heliostatic** [comment]
Great to hear! Basically, I have a couple files that get automatically updated, so the block ref counts are inaccurate -- 
![2022-11-04 at 12 39 46 - Obsidian - CleanShot](https://user-images.githubusercontent.com/70898/200030093-b8fd17ba-053d-4d47-afdc-9ef4f1409df2.png)

**Comment by TfTHacker** [comment]
With 1.0.5 it is now possible to mark files in the frontmatter so they won't be included in the Index. Check this out:

https://github.com/TfTHacker/obsidian42-strange-new-worlds#snw-frontmatter-directives

I am still debating about folder exclusion. So I am going to close this out for now, since I will have this in mind for the future.
