### ISSUE TITLE
Bug: Conflict with Ozan's Image in Editor Plugin...

### ISSUE THREAD

**Issue by olearydj** [TfTHacker/obsidian42-strange-new-worlds#68]
Obsidian 1.1.6 with installer 1.0.3
Ozan's Image in Editor (OIE) 2.1.5 (https://github.com/ozntel/oz-image-in-editor-obsidian)
SNW 1.1.1
Shimmering Focus or Default Theme
Not legacy editor

With the above configuration, linked local images, e.g. `![[pasted image.png]]`, OIE is not able to display them in edit mode. When I disable SNW, it works as expected. I've confirmed this in both my normal theme (SF) and the default one.

This bug seems to have been introduced recently as I've used the combination for a while now without issue.

Thanks for all you do for the TfT community.

**Comment by TfTHacker** [comment]
I tested this with a recent version of SNW coming out in a few days (1.2.0) and I couldn't duplicate the problem. Plus I see Ozan's Image in Editor has been updated, so possibly the problem resolved itself. Please try again in a few days once 1.2.0 is out and reopen this issue if the problem is not resolved.

Tnx for reporting it!
