### ISSUE TITLE
The plugin causes an indent in Editing view

### ISSUE THREAD

**Issue by kandyman2017** [TfTHacker/obsidian42-strange-new-worlds#78]
When I installed the plugin, it caused an issue where all text in Editing view was indented, causing a misalignment with Reading view. 
![editing mode](https://user-images.githubusercontent.com/32620963/218318182-fd93bad3-f2cd-4f5a-b3c3-363b981beee8.jpg)
![preview mode](https://user-images.githubusercontent.com/32620963/218318189-f4f4d4a3-1733-4030-9664-b0ebf6974db2.jpg)

**Comment by Yubuxin** [comment]
Same issue.

**Comment by TfTHacker** [comment]
Some themes have this issue, for example, the default ones, though minimal doesn't for example.

It's not really a bug because these themes define a gutter area if there is something for the gutter. SNW by default has gutter. This can be turned off with this feature:

<img width="616" alt="CleanShot 2023-03-03 at 11 45 03@2x" src="https://user-images.githubusercontent.com/69121180/222700781-7f0b8ec2-3bf7-4fb9-92c9-fa20ad4381d3.png">
