### ISSUE TITLE
Feature Request: Automatically update the referer's link when the referee is moved to another file

### ISSUE THREAD

**Issue by tristone13th** [TfTHacker/obsidian42-strange-new-worlds#85]
Suppose I have 2 files, A and B. and A refers to a heading in B in the wiki link way ([[ The Link]]).

The problem is

- when I move the heading from B to another file, C, then the link in A will be invalid.
- when I rename B to another name, then the link in A will also be invalid.

Is there any way to handle this? if not, I think this may be a useful enhancement for considering~

**Comment by TfTHacker** [comment]
I think this is more of an issue with Obsidian. Obsidian doesn't have the concept of moving headings to another file and updating the links to that heading. Actually, if you rename a heading in a file it will break links to that heading unless you used the "Rename Heading" feature (see: https://forum.obsidian.md/t/obsidian-release-v0-12-14/23046)

Otherwise, this is beyond the scope of SNW. I think if it were easy to do, Obsidian would already have it in core.

See: 
+ https://forum.obsidian.md/t/how-to-update-links-when-header-is-spun-off-into-its-own-note/26917/2
+ https://forum.obsidian.md/t/update-links-to-section-headings-after-automatic-rename/24016
